/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world.opentexts.util;

/**
 * Convert a 008 field into a language field (e.g. spa -> Spanish)
 * 
 * @author Stuart Lewis
 */
public class MARC21LanguageCodeLookup {
    public static String convert(String language) {
        if (language.equals("")) return "Undetermined";
        else if (language.equals("aar")) return "Afar";
        else if (language.equals("abk")) return "Abkhaz";
        else if (language.equals("ace")) return "Achinese";
        else if (language.equals("ach")) return "Acoli";
        else if (language.equals("ada")) return "Adangme";
        else if (language.equals("ady")) return "Adygei";
        else if (language.equals("afa")) return "Afroasiatic (Other)";
        else if (language.equals("afh")) return "Afrihili (Artificial language)";
        else if (language.equals("afr")) return "Afrikaans";
        else if (language.equals("ain")) return "Ainu";
        else if (language.equals("-ajm")) return "Aljamía";
        else if (language.equals("aka")) return "Akan";
        else if (language.equals("akk")) return "Akkadian";
        else if (language.equals("alb")) return "Albanian";
        else if (language.equals("ale")) return "Aleut";
        else if (language.equals("alg")) return "Algonquian (Other)";
        else if (language.equals("alt")) return "Altai";
        else if (language.equals("amh")) return "Amharic";
        else if (language.equals("ang")) return "English, Old (ca. 450-1100)";
        else if (language.equals("anp")) return "Angika";
        else if (language.equals("apa")) return "Apache languages";
        else if (language.equals("ara")) return "Arabic";
        else if (language.equals("arc")) return "Aramaic";
        else if (language.equals("arg")) return "Aragonese";
        else if (language.equals("arm")) return "Armenian";
        else if (language.equals("arn")) return "Mapuche";
        else if (language.equals("arp")) return "Arapaho";
        else if (language.equals("art")) return "Artificial (Other)";
        else if (language.equals("arw")) return "Arawak";
        else if (language.equals("asm")) return "Assamese";
        else if (language.equals("ast")) return "Bable";
        else if (language.equals("ath")) return "Athapascan (Other)";
        else if (language.equals("aus")) return "Australian languages";
        else if (language.equals("ava")) return "Avaric";
        else if (language.equals("ave")) return "Avestan";
        else if (language.equals("awa")) return "Awadhi";
        else if (language.equals("aym")) return "Aymara";
        else if (language.equals("aze")) return "Azerbaijani";
        else if (language.equals("bad")) return "Banda languages";
        else if (language.equals("bai")) return "Bamileke languages";
        else if (language.equals("bak")) return "Bashkir";
        else if (language.equals("bal")) return "Baluchi";
        else if (language.equals("bam")) return "Bambara";
        else if (language.equals("ban")) return "Balinese";
        else if (language.equals("baq")) return "Basque";
        else if (language.equals("bas")) return "Basa";
        else if (language.equals("bat")) return "Baltic (Other)";
        else if (language.equals("bej")) return "Beja";
        else if (language.equals("bel")) return "Belarusian";
        else if (language.equals("bem")) return "Bemba";
        else if (language.equals("ben")) return "Bengali";
        else if (language.equals("ber")) return "Berber (Other)";
        else if (language.equals("bho")) return "Bhojpuri";
        else if (language.equals("bih")) return "Bihari (Other)";
        else if (language.equals("bik")) return "Bikol";
        else if (language.equals("bin")) return "Edo";
        else if (language.equals("bis")) return "Bislama";
        else if (language.equals("bla")) return "Siksika";
        else if (language.equals("bnt")) return "Bantu (Other)";
        else if (language.equals("bos")) return "Bosnian";
        else if (language.equals("bra")) return "Braj";
        else if (language.equals("bre")) return "Breton";
        else if (language.equals("btk")) return "Batak";
        else if (language.equals("bua")) return "Buriat";
        else if (language.equals("bug")) return "Bugis";
        else if (language.equals("bul")) return "Bulgarian";
        else if (language.equals("bur")) return "Burmese";
        else if (language.equals("byn")) return "Bilin";
        else if (language.equals("cad")) return "Caddo";
        else if (language.equals("cai")) return "Central American Indian (Other)";
        else if (language.equals("-cam")) return "Khmer";
        else if (language.equals("car")) return "Carib";
        else if (language.equals("cat")) return "Catalan";
        else if (language.equals("cau")) return "Caucasian (Other)";
        else if (language.equals("ceb")) return "Cebuano";
        else if (language.equals("cel")) return "Celtic (Other)";
        else if (language.equals("cha")) return "Chamorro";
        else if (language.equals("chb")) return "Chibcha";
        else if (language.equals("che")) return "Chechen";
        else if (language.equals("chg")) return "Chagatai";
        else if (language.equals("chi")) return "Chinese";
        else if (language.equals("chk")) return "Chuukese";
        else if (language.equals("chm")) return "Mari";
        else if (language.equals("chn")) return "Chinook jargon";
        else if (language.equals("cho")) return "Choctaw";
        else if (language.equals("chp")) return "Chipewyan";
        else if (language.equals("chr")) return "Cherokee";
        else if (language.equals("chu")) return "Church Slavic";
        else if (language.equals("chv")) return "Chuvash";
        else if (language.equals("chy")) return "Cheyenne";
        else if (language.equals("cmc")) return "Chamic languages";
        else if (language.equals("cnr")) return "Montenegrin";
        else if (language.equals("cop")) return "Coptic";
        else if (language.equals("cor")) return "Cornish";
        else if (language.equals("cos")) return "Corsican";
        else if (language.equals("cpe")) return "Creoles and Pidgins, English-based (Other)";
        else if (language.equals("cpf")) return "Creoles and Pidgins, French-based (Other)";
        else if (language.equals("cpp")) return "Creoles and Pidgins, Portuguese-based (Other)";
        else if (language.equals("cre")) return "Cree";
        else if (language.equals("crh")) return "Crimean Tatar";
        else if (language.equals("crp")) return "Creoles and Pidgins (Other)";
        else if (language.equals("csb")) return "Kashubian";
        else if (language.equals("cus")) return "Cushitic (Other)";
        else if (language.equals("cze")) return "Czech";
        else if (language.equals("dak")) return "Dakota";
        else if (language.equals("dan")) return "Danish";
        else if (language.equals("dar")) return "Dargwa";
        else if (language.equals("day")) return "Dayak";
        else if (language.equals("del")) return "Delaware";
        else if (language.equals("den")) return "Slavey";
        else if (language.equals("dgr")) return "Dogrib";
        else if (language.equals("din")) return "Dinka";
        else if (language.equals("div")) return "Divehi";
        else if (language.equals("doi")) return "Dogri";
        else if (language.equals("dra")) return "Dravidian (Other)";
        else if (language.equals("dsb")) return "Lower Sorbian";
        else if (language.equals("dua")) return "Duala";
        else if (language.equals("dum")) return "Dutch, Middle (ca. 1050-1350)";
        else if (language.equals("dut")) return "Dutch";
        else if (language.equals("dyu")) return "Dyula";
        else if (language.equals("dzo")) return "Dzongkha";
        else if (language.equals("efi")) return "Efik";
        else if (language.equals("egy")) return "Egyptian";
        else if (language.equals("eka")) return "Ekajuk";
        else if (language.equals("elx")) return "Elamite";
        else if (language.equals("eng")) return "English";
        else if (language.equals("enm")) return "English, Middle (1100-1500)";
        else if (language.equals("epo")) return "Esperanto";
        else if (language.equals("-esk")) return "Eskimo languages";
        else if (language.equals("-esp")) return "Esperanto";
        else if (language.equals("est")) return "Estonian";
        else if (language.equals("-eth")) return "Ethiopic";
        else if (language.equals("ewe")) return "Ewe";
        else if (language.equals("ewo")) return "Ewondo";
        else if (language.equals("fan")) return "Fang";
        else if (language.equals("fao")) return "Faroese";
        else if (language.equals("-far")) return "Faroese";
        else if (language.equals("fat")) return "Fanti";
        else if (language.equals("fij")) return "Fijian";
        else if (language.equals("fil")) return "Filipino";
        else if (language.equals("fin")) return "Finnish";
        else if (language.equals("fiu")) return "Finno-Ugrian (Other)";
        else if (language.equals("fon")) return "Fon";
        else if (language.equals("fre")) return "French";
        else if (language.equals("-fri")) return "Frisian";
        else if (language.equals("frm")) return "French, Middle (ca. 1300-1600)";
        else if (language.equals("fro")) return "French, Old (ca. 842-1300)";
        else if (language.equals("frr")) return "North Frisian";
        else if (language.equals("frs")) return "East Frisian";
        else if (language.equals("fry")) return "Frisian";
        else if (language.equals("ful")) return "Fula";
        else if (language.equals("fur")) return "Friulian";
        else if (language.equals("gaa")) return "Gã";
        else if (language.equals("-gae")) return "Scottish Gaelix";
        else if (language.equals("-gag")) return "Galician";
        else if (language.equals("-gal")) return "Oromo";
        else if (language.equals("gay")) return "Gayo";
        else if (language.equals("gba")) return "Gbaya";
        else if (language.equals("gem")) return "Germanic (Other)";
        else if (language.equals("geo")) return "Georgian";
        else if (language.equals("ger")) return "German";
        else if (language.equals("gez")) return "Ethiopic";
        else if (language.equals("gil")) return "Gilbertese";
        else if (language.equals("gla")) return "Scottish Gaelic";
        else if (language.equals("gle")) return "Irish";
        else if (language.equals("glg")) return "Galician";
        else if (language.equals("glv")) return "Manx";
        else if (language.equals("gmh")) return "German, Middle High (ca. 1050-1500)";
        else if (language.equals("goh")) return "German, Old High (ca. 750-1050)";
        else if (language.equals("gon")) return "Gondi";
        else if (language.equals("gor")) return "Gorontalo";
        else if (language.equals("got")) return "Gothic";
        else if (language.equals("grb")) return "Grebo";
        else if (language.equals("grc")) return "Greek, Ancient (to 1453)";
        else if (language.equals("gre")) return "Greek, Modern (1453-)";
        else if (language.equals("grn")) return "Guarani";
        else if (language.equals("gsw")) return "Swiss German";
        else if (language.equals("-gua")) return "Guarani";
        else if (language.equals("guj")) return "Gujarati";
        else if (language.equals("gwi")) return "Gwich'in";
        else if (language.equals("hai")) return "Haida";
        else if (language.equals("hat")) return "Haitian French Creole";
        else if (language.equals("hau")) return "Hausa";
        else if (language.equals("haw")) return "Hawaiian";
        else if (language.equals("heb")) return "Hebrew";
        else if (language.equals("her")) return "Herero";
        else if (language.equals("hil")) return "Hiligaynon";
        else if (language.equals("him")) return "Western Pahari languages";
        else if (language.equals("hin")) return "Hindi";
        else if (language.equals("hit")) return "Hittite";
        else if (language.equals("hmn")) return "Hmong";
        else if (language.equals("hmo")) return "Hiri Motu";
        else if (language.equals("hrv")) return "Croatian";
        else if (language.equals("hsb")) return "Upper Sorbian";
        else if (language.equals("hun")) return "Hungarian";
        else if (language.equals("hup")) return "Hupa";
        else if (language.equals("iba")) return "Iban";
        else if (language.equals("ibo")) return "Igbo";
        else if (language.equals("ice")) return "Icelandic";
        else if (language.equals("ido")) return "Ido";
        else if (language.equals("iii")) return "Sichuan Yi";
        else if (language.equals("ijo")) return "Ijo";
        else if (language.equals("iku")) return "Inuktitut";
        else if (language.equals("ile")) return "Interlingue";
        else if (language.equals("ilo")) return "Iloko";
        else if (language.equals("ina")) return "Interlingua (International Auxiliary Language Association)";
        else if (language.equals("inc")) return "Indic (Other)";
        else if (language.equals("ind")) return "Indonesian";
        else if (language.equals("ine")) return "Indo-European (Other)";
        else if (language.equals("inh")) return "Ingush";
        else if (language.equals("-int")) return "Interlingua (International Auxiliary Language Association)";
        else if (language.equals("ipk")) return "Inupiaq";
        else if (language.equals("ira")) return "Iranian (Other)";
        else if (language.equals("-iri")) return "Irish";
        else if (language.equals("iro")) return "Iroquoian (Other)";
        else if (language.equals("ita")) return "Italian";
        else if (language.equals("jav")) return "Javanese";
        else if (language.equals("jbo")) return "Lojban (Artificial language)";
        else if (language.equals("jpn")) return "Japanese";
        else if (language.equals("jpr")) return "Judeo-Persian";
        else if (language.equals("jrb")) return "Judeo-Arabic";
        else if (language.equals("kaa")) return "Kara-Kalpak";
        else if (language.equals("kab")) return "Kabyle";
        else if (language.equals("kac")) return "Kachin";
        else if (language.equals("kal")) return "Kalâtdlisut";
        else if (language.equals("kam")) return "Kamba";
        else if (language.equals("kan")) return "Kannada";
        else if (language.equals("kar")) return "Karen languages";
        else if (language.equals("kas")) return "Kashmiri";
        else if (language.equals("kau")) return "Kanuri";
        else if (language.equals("kaw")) return "Kawi";
        else if (language.equals("kaz")) return "Kazakh";
        else if (language.equals("kbd")) return "Kabardian";
        else if (language.equals("kha")) return "Khasi";
        else if (language.equals("khi")) return "Khoisan (Other)";
        else if (language.equals("khm")) return "Khmer";
        else if (language.equals("kho")) return "Khotanese";
        else if (language.equals("kik")) return "Kikuyu";
        else if (language.equals("kin")) return "Kinyarwanda";
        else if (language.equals("kir")) return "Kyrgyz";
        else if (language.equals("kmb")) return "Kimbundu";
        else if (language.equals("kok")) return "Konkani";
        else if (language.equals("kom")) return "Komi";
        else if (language.equals("kon")) return "Kongo";
        else if (language.equals("kor")) return "Korean";
        else if (language.equals("kos")) return "Kosraean";
        else if (language.equals("kpe")) return "Kpelle";
        else if (language.equals("krc")) return "Karachay-Balkar";
        else if (language.equals("krl")) return "Karelian";
        else if (language.equals("kro")) return "Kru (Other)";
        else if (language.equals("kru")) return "Kurukh";
        else if (language.equals("kua")) return "Kuanyama";
        else if (language.equals("kum")) return "Kumyk";
        else if (language.equals("kur")) return "Kurdish";
        else if (language.equals("-kus")) return "Kusaie";
        else if (language.equals("kut")) return "Kootenai";
        else if (language.equals("lad")) return "Ladino";
        else if (language.equals("lah")) return "Lahndā";
        else if (language.equals("lam")) return "Lamba (Zambia and Congo)";
        else if (language.equals("-lan")) return "Occitan (post 1500)";
        else if (language.equals("lao")) return "Lao";
        else if (language.equals("-lap")) return "Sami";
        else if (language.equals("lat")) return "Latin";
        else if (language.equals("lav")) return "Latvian";
        else if (language.equals("lez")) return "Lezgian";
        else if (language.equals("lim")) return "Limburgish";
        else if (language.equals("lin")) return "Lingala";
        else if (language.equals("lit")) return "Lithuanian";
        else if (language.equals("lol")) return "Mongo-Nkundu";
        else if (language.equals("loz")) return "Lozi";
        else if (language.equals("ltz")) return "Luxembourgish";
        else if (language.equals("lua")) return "Luba-Lulua";
        else if (language.equals("lub")) return "Luba-Katanga";
        else if (language.equals("lug")) return "Ganda";
        else if (language.equals("lui")) return "Luiseño";
        else if (language.equals("lun")) return "Lunda";
        else if (language.equals("luo")) return "Luo (Kenya and Tanzania)";
        else if (language.equals("lus")) return "Lushai";
        else if (language.equals("mac")) return "Macedonian";
        else if (language.equals("mad")) return "Madurese";
        else if (language.equals("mag")) return "Magahi";
        else if (language.equals("mah")) return "Marshallese";
        else if (language.equals("mai")) return "Maithili";
        else if (language.equals("mak")) return "Makasar";
        else if (language.equals("mal")) return "Malayalam";
        else if (language.equals("man")) return "Mandingo";
        else if (language.equals("mao")) return "Maori";
        else if (language.equals("map")) return "Austronesian (Other)";
        else if (language.equals("mar")) return "Marathi";
        else if (language.equals("mas")) return "Maasai";
        else if (language.equals("-max")) return "Manx";
        else if (language.equals("may")) return "Malay";
        else if (language.equals("mdf")) return "Moksha";
        else if (language.equals("mdr")) return "Mandar";
        else if (language.equals("men")) return "Mende";
        else if (language.equals("mga")) return "Irish, Middle (ca. 1100-1550)";
        else if (language.equals("mic")) return "Micmac";
        else if (language.equals("min")) return "Minangkabau";
        else if (language.equals("mis")) return "Miscellaneous languages";
        else if (language.equals("mkh")) return "Mon-Khmer (Other)";
        else if (language.equals("-mla")) return "Malagasy";
        else if (language.equals("mlg")) return "Malagasy";
        else if (language.equals("mlt")) return "Maltese";
        else if (language.equals("mnc")) return "Manchu";
        else if (language.equals("mni")) return "Manipuri";
        else if (language.equals("mno")) return "Manobo languages";
        else if (language.equals("moh")) return "Mohawk";
        else if (language.equals("-mol")) return "Moldavian";
        else if (language.equals("mon")) return "Mongolian";
        else if (language.equals("mos")) return "Mooré";
        else if (language.equals("mul")) return "Multiple languages";
        else if (language.equals("mun")) return "Munda (Other)";
        else if (language.equals("mus")) return "Creek";
        else if (language.equals("mwl")) return "Mirandese";
        else if (language.equals("mwr")) return "Marwari";
        else if (language.equals("myn")) return "Mayan languages";
        else if (language.equals("myv")) return "Erzya";
        else if (language.equals("nah")) return "Nahuatl";
        else if (language.equals("nai")) return "North American Indian (Other)";
        else if (language.equals("nap")) return "Neapolitan Italian";
        else if (language.equals("nau")) return "Nauru";
        else if (language.equals("nav")) return "Navajo";
        else if (language.equals("nbl")) return "Ndebele (South Africa)";
        else if (language.equals("nde")) return "Ndebele (Zimbabwe)";
        else if (language.equals("ndo")) return "Ndonga";
        else if (language.equals("nds")) return "Low German";
        else if (language.equals("nep")) return "Nepali";
        else if (language.equals("new")) return "Newari";
        else if (language.equals("nia")) return "Nias";
        else if (language.equals("nic")) return "Niger-Kordofanian (Other)";
        else if (language.equals("niu")) return "Niuean";
        else if (language.equals("nno")) return "Norwegian (Nynorsk)";
        else if (language.equals("nob")) return "Norwegian (Bokmål)";
        else if (language.equals("nog")) return "Nogai";
        else if (language.equals("non")) return "Old Norse";
        else if (language.equals("nor")) return "Norwegian";
        else if (language.equals("nqo")) return "N'Ko";
        else if (language.equals("nso")) return "Northern Sotho";
        else if (language.equals("nub")) return "Nubian languages";
        else if (language.equals("nwc")) return "Newari, Old";
        else if (language.equals("nya")) return "Nyanja";
        else if (language.equals("nym")) return "Nyamwezi";
        else if (language.equals("nyn")) return "Nyankole";
        else if (language.equals("nyo")) return "Nyoro";
        else if (language.equals("nzi")) return "Nzima";
        else if (language.equals("oci")) return "Occitan (post-1500)";
        else if (language.equals("oji")) return "Ojibwa";
        else if (language.equals("ori")) return "Oriya";
        else if (language.equals("orm")) return "Oromo";
        else if (language.equals("osa")) return "Osage";
        else if (language.equals("oss")) return "Ossetic";
        else if (language.equals("ota")) return "Turkish, Ottoman";
        else if (language.equals("oto")) return "Otomian languages";
        else if (language.equals("paa")) return "Papuan (Other)";
        else if (language.equals("pag")) return "Pangasinan";
        else if (language.equals("pal")) return "Pahlavi";
        else if (language.equals("pam")) return "Pampanga";
        else if (language.equals("pan")) return "Panjabi";
        else if (language.equals("pap")) return "Papiamento";
        else if (language.equals("pau")) return "Palauan";
        else if (language.equals("peo")) return "Old Persian (ca. 600-400 B.C.)";
        else if (language.equals("per")) return "Persian";
        else if (language.equals("phi")) return "Philippine (Other)";
        else if (language.equals("phn")) return "Phoenician";
        else if (language.equals("pli")) return "Pali";
        else if (language.equals("pol")) return "Polish";
        else if (language.equals("pon")) return "Pohnpeian";
        else if (language.equals("por")) return "Portuguese";
        else if (language.equals("pra")) return "Prakrit languages";
        else if (language.equals("pro")) return "Provençal (to 1500)";
        else if (language.equals("pus")) return "Pushto";
        else if (language.equals("que")) return "Quechua";
        else if (language.equals("raj")) return "Rajasthani";
        else if (language.equals("rap")) return "Rapanui";
        else if (language.equals("rar")) return "Rarotongan";
        else if (language.equals("roa")) return "Romance (Other)";
        else if (language.equals("roh")) return "Raeto-Romance";
        else if (language.equals("rom")) return "Romani";
        else if (language.equals("rum")) return "Romanian";
        else if (language.equals("run")) return "Rundi";
        else if (language.equals("rup")) return "Aromanian";
        else if (language.equals("rus")) return "Russian";
        else if (language.equals("sad")) return "Sandawe";
        else if (language.equals("sag")) return "Sango (Ubangi Creole)";
        else if (language.equals("sah")) return "Yakut";
        else if (language.equals("sai")) return "South American Indian (Other)";
        else if (language.equals("sal")) return "Salishan languages";
        else if (language.equals("sam")) return "Samaritan Aramaic";
        else if (language.equals("san")) return "Sanskrit";
        else if (language.equals("-sao")) return "Samoan";
        else if (language.equals("sas")) return "Sasak";
        else if (language.equals("sat")) return "Santali";
        else if (language.equals("-scc")) return "Serbian";
        else if (language.equals("scn")) return "Sicilian Italian";
        else if (language.equals("sco")) return "Scots";
        else if (language.equals("-scr")) return "Croatian";
        else if (language.equals("sel")) return "Selkup";
        else if (language.equals("sem")) return "Semitic (Other)";
        else if (language.equals("sga")) return "Irish, Old (to 1100)";
        else if (language.equals("sgn")) return "Sign languages";
        else if (language.equals("shn")) return "Shan";
        else if (language.equals("-sho")) return "Shona";
        else if (language.equals("sid")) return "Sidamo";
        else if (language.equals("sin")) return "Sinhalese";
        else if (language.equals("sio")) return "Siouan (Other)";
        else if (language.equals("sit")) return "Sino-Tibetan (Other)";
        else if (language.equals("sla")) return "Slavic (Other)";
        else if (language.equals("slo")) return "Slovak";
        else if (language.equals("slv")) return "Slovenian";
        else if (language.equals("sma")) return "Southern Sami";
        else if (language.equals("sme")) return "Northern Sami";
        else if (language.equals("smi")) return "Sami";
        else if (language.equals("smj")) return "Lule Sami";
        else if (language.equals("smn")) return "Inari Sami";
        else if (language.equals("smo")) return "Samoan";
        else if (language.equals("sms")) return "Skolt Sami";
        else if (language.equals("sna")) return "Shona";
        else if (language.equals("snd")) return "Sindhi";
        else if (language.equals("-snh")) return "Sinhalese";
        else if (language.equals("snk")) return "Soninke";
        else if (language.equals("sog")) return "Sogdian";
        else if (language.equals("som")) return "Somali";
        else if (language.equals("son")) return "Songhai";
        else if (language.equals("sot")) return "Sotho";
        else if (language.equals("spa")) return "Spanish";
        else if (language.equals("srd")) return "Sardinian";
        else if (language.equals("srn")) return "Sranan";
        else if (language.equals("srp")) return "Serbian";
        else if (language.equals("srr")) return "Serer";
        else if (language.equals("ssa")) return "Nilo-Saharan (Other)";
        else if (language.equals("-sso")) return "Sotho";
        else if (language.equals("ssw")) return "Swazi";
        else if (language.equals("suk")) return "Sukuma";
        else if (language.equals("sun")) return "Sundanese";
        else if (language.equals("sus")) return "Susu";
        else if (language.equals("sux")) return "Sumerian";
        else if (language.equals("swa")) return "Swahili";
        else if (language.equals("swe")) return "Swedish";
        else if (language.equals("-swz")) return "Swazi";
        else if (language.equals("syc")) return "Syriac";
        else if (language.equals("syr")) return "Syriac, Modern";
        else if (language.equals("-tag")) return "Tagalog";
        else if (language.equals("tah")) return "Tahitian";
        else if (language.equals("tai")) return "Tai (Other)";
        else if (language.equals("-taj")) return "Tajik";
        else if (language.equals("tam")) return "Tamil";
        else if (language.equals("-tar")) return "Tatar";
        else if (language.equals("tat")) return "Tatar";
        else if (language.equals("tel")) return "Telugu";
        else if (language.equals("tem")) return "Temne";
        else if (language.equals("ter")) return "Terena";
        else if (language.equals("tet")) return "Tetum";
        else if (language.equals("tgk")) return "Tajik";
        else if (language.equals("tgl")) return "Tagalog";
        else if (language.equals("tha")) return "Thai";
        else if (language.equals("tib")) return "Tibetan";
        else if (language.equals("tig")) return "Tigré";
        else if (language.equals("tir")) return "Tigrinya";
        else if (language.equals("tiv")) return "Tiv";
        else if (language.equals("tkl")) return "Tokelauan";
        else if (language.equals("tlh")) return "Klingon (Artificial language)";
        else if (language.equals("tli")) return "Tlingit";
        else if (language.equals("tmh")) return "Tamashek";
        else if (language.equals("tog")) return "Tonga (Nyasa)";
        else if (language.equals("ton")) return "Tongan";
        else if (language.equals("tpi")) return "Tok Pisin";
        else if (language.equals("-tru")) return "Truk";
        else if (language.equals("tsi")) return "Tsimshian";
        else if (language.equals("tsn")) return "Tswana";
        else if (language.equals("tso")) return "Tsonga";
        else if (language.equals("-tsw")) return "Tswana";
        else if (language.equals("tuk")) return "Turkmen";
        else if (language.equals("tum")) return "Tumbuka";
        else if (language.equals("tup")) return "Tupi languages";
        else if (language.equals("tur")) return "Turkish";
        else if (language.equals("tut")) return "Altaic (Other)";
        else if (language.equals("tvl")) return "Tuvaluan";
        else if (language.equals("twi")) return "Twi";
        else if (language.equals("tyv")) return "Tuvinian";
        else if (language.equals("udm")) return "Udmurt";
        else if (language.equals("uga")) return "Ugaritic";
        else if (language.equals("uig")) return "Uighur";
        else if (language.equals("ukr")) return "Ukrainian";
        else if (language.equals("umb")) return "Umbundu";
        else if (language.equals("und")) return "Undetermined";
        else if (language.equals("urd")) return "Urdu";
        else if (language.equals("uzb")) return "Uzbek";
        else if (language.equals("vai")) return "Vai";
        else if (language.equals("ven")) return "Venda";
        else if (language.equals("vie")) return "Vietnamese";
        else if (language.equals("vol")) return "Volapük";
        else if (language.equals("vot")) return "Votic";
        else if (language.equals("wak")) return "Wakashan languages";
        else if (language.equals("wal")) return "Wolayta";
        else if (language.equals("war")) return "Waray";
        else if (language.equals("was")) return "Washoe";
        else if (language.equals("wel")) return "Welsh";
        else if (language.equals("wen")) return "Sorbian (Other)";
        else if (language.equals("wln")) return "Walloon";
        else if (language.equals("wol")) return "Wolof";
        else if (language.equals("xal")) return "Oirat";
        else if (language.equals("xho")) return "Xhosa";
        else if (language.equals("yao")) return "Yao (Africa)";
        else if (language.equals("yap")) return "Yapese";
        else if (language.equals("yid")) return "Yiddish";
        else if (language.equals("yor")) return "Yoruba";
        else if (language.equals("ypk")) return "Yupik languages";
        else if (language.equals("zap")) return "Zapotec";
        else if (language.equals("zbl")) return "Blissymbolics";
        else if (language.equals("zen")) return "Zenaga";
        else if (language.equals("zha")) return "Zhuang";
        else if (language.equals("znd")) return "Zande languages";
        else if (language.equals("zul")) return "Zulu";
        else if (language.equals("zun")) return "Zuni";
        else if (language.equals("zxx")) return "No linguistic content";
        else if (language.equals("zza")) return "Zaza";
        else {
            // Jsut stop for now
            System.err.println(" - Unknown language: " + language);
            return "Undetermined";
        }
    }
}
